"""add admin reply to suggestions

Revision ID: 29f80f64d222
Revises: 54b4837e6f4c
Create Date: 2026-08-23 12:29:34.531793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f80f64d222'
down_revision: Union[str, Sequence[str], None] = '54b4837e6f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('admin_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestions', 'admin_reply')
    # ### end Alembic commands ###
