"""add_issue_reason_to_assignments

Revision ID: f50db405c00c
Revises: 9f9ec60f9a24
Create Date: 2026-09-13 01:58:15.838281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50db405c00c'
down_revision: Union[str, Sequence[str], None] = '9f9ec60f9a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('issue_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'issue_reason')
    # ### end Alembic commands ###
