from app.models.user import User
from app.models.waste_bin import WasteBin
from app.models.concern import Concern
from app.models.concern_image import ConcernImage
from app.models.concern_support import ConcernSupport
from app.models.concern_history import ConcernHistory
from app.models.assignment import Assignment
from app.models.notification import Notification
from app.models.collection_route import CollectionRoute
from app.models.collection_point import CollectionPoint
from app.models.suggestion import Suggestion