"""make waste_bin_id nullable on collection_points

Revision ID: ab59c2b93fec
Revises: 4bb29281c9ca
Create Date: 2026-08-31 11:51:12.918879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab59c2b93fec'
down_revision: Union[str, Sequence[str], None] = '4bb29281c9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_points', 'waste_bin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('collection_points_waste_bin_id_fkey'), 'collection_points', type_='foreignkey')
    op.create_foreign_key(None, 'collection_points', 'waste_bins', ['waste_bin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection_points', type_='foreignkey')
    op.create_foreign_key(op.f('collection_points_waste_bin_id_fkey'), 'collection_points', 'waste_bins', ['waste_bin_id'], ['id'], ondelete='CASCADE')
    op.alter_column('collection_points', 'waste_bin_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
